services:
  

  flower_scrap:
    image: mher/flower
    container_name: flower_scrap
    environment:
      - CELERY_BROKER_URL=amqp://admin:admin@rabbitmq:5672//
    ports:
      - "5556:5555"
    depends_on:
      rabbitmq:
        condition: service_started
    

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ
      - "15672:15672" # Management interface
    environment:
      RABBITMQ_URL: rabbitmq
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    restart: always
